### ISSUE TITLE
Uploading file to the OneDrive

### ISSUE THREAD

**Issue by eugenesmkn** [tawalaya/OneDriveJavaSDK#2]
Hi!
I try to upload file to OneDrive using sdk but when I (sdk) create UploadSession, it fails with access denied.

Could you, please, help me with it?
Any suggestion or examples would be helpful.
Thank you!

**Comment by Timmeey** [comment]
It worked 2 years ago ;-)

Microsoft has probably changed its API since then. Especially because the async/chunked file upload API/Documentation already seemed a little bit fiddly back then.

Unfortunately the project is unmaintained for now.

**Comment by eugenesmkn** [comment]
Thank you for your response!
I figure out what I'm doing wrong - I request not all permissions from OneDrive

**Comment by hamedisu** [comment]
Hi
I'm totally new to java and mircosoft graph.
I want to upload a file on my drive with java programmatically .
would you please give me a simple code to do that?
many thanks in advance
