### ISSUE TITLE
Create path in one call

### ISSUE THREAD

**Issue by aliasdoc** [tawalaya/OneDriveJavaSDK#3]
Hi,

I'm trying to create a path to upload a file like this:
foo/bar/baz/qux/quux/myfile.txt and the only way I found it work qith this SDK is to create folders separately and upload my file.

pseudo code:

```
get root folder -> create folder 1
get folder 1 -> create folder 2
get folder 2 -> create folder 3
get folder 3 -> upload my file
```

Is there a simple way to do this ?

Thank you.

**Comment by Timmeey** [comment]
Thank you @aliasdoc for your feedback.

As this was only a academic project that is not maintained for 2 years now, i don't think there is another way.

I'm actually quite surprised that this SDK is still working with the API.

But PRs are quite welcome, then i will take the time to review/merge it.

**Comment by aliasdoc** [comment]
Hi @Timmeey, thank you for your reply.
I found this library very useful and it's a good job ;). I try to add this  feature and send you a PR.
